image: python:3.7

variables:
  PYTHON_TAG: py3
  ABI_TAG: none
  PLATFORM_TAG: any
  PACKAGE_EXTENSION: whl

stages:
  - build
  - deploy

build:
  stage: build
  script:
    # Get version. Variable CI_COMMIT_TAG is set only when tag was pushed.
    - export VERSION=$(if [[ "$CI_COMMIT_TAG" == "" ]]; then echo 0.0.0; else echo $CI_COMMIT_TAG | cut -c 2-; fi)
    - python3 setup.py setopt --command=metadata --option=version --set-value=$VERSION
    - echo VERSION=$VERSION
    - cat setup.py
    # Get package filename
    - export WHEEL_NAME=$(python3 setup.py --name | tr '-' '_')
    - export PACKAGE=$WHEEL_NAME-$VERSION-$PYTHON_TAG-$ABI_TAG-$PLATFORM_TAG.$PACKAGE_EXTENSION
    - echo PACKAGE=$PACKAGE
    - python3 setup.py bdist_wheel
    - echo $PACKAGE > dist/.package-name
    - ls -la
    - ls -ls dist

  only:
    - branches
    - tags
  tags:
    - shared-fi
  artifacts:
    paths:
      - dist
    expire_in: 1 day

deploy:
  stage: deploy
  script:
    - echo "[distutils]" >> ~/.pypirc
    - echo "index-servers = gitlab" >> ~/.pypirc
    - echo "[gitlab]" >> ~/.pypirc
    - space=" "
    - echo "repository :$space https://gitlab.fi.muni.cz/api/v4/projects/14820/packages/pypi" >> ~/.pypirc
    - echo "username = __token__" >> ~/.pypirc
    - echo "password = $api_token" >> ~/.pypirc
    - echo 'import requests,sys' >> remover.py
    - python3 -m pip install --user --upgrade twine
    - echo "requests.delete('https://gitlab.fi.muni.cz/api/v4/projects/14820/packages/'+str(requests.get('https://gitlab.fi.muni.cz/api/v4/projects/14820/packages', headers={'PRIVATE-TOKEN':sys.argv[1],}).json()[-1]['id']), headers={'PRIVATE-TOKEN':sys.argv[1],})" >> remover.py
    - python -m twine upload --repository gitlab dist/*
  dependencies:
    - build
  only:
    - tags
    - branches
  tags:
    - shared-fi
