image: python:3.8

variables:
  PYTHON_TAG: py3
  ABI_TAG: none
  PLATFORM_TAG: any
  PACKAGE_EXTENSION: whl

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - pip3 install pipenv
    - pipenv sync
    - pipenv run coverage run -m pytest

  only:
    - branches
    - tags

build:
  stage: build
  script:
    # Get version. Variable CI_COMMIT_TAG is set only when tag was pushed.
    - export LATEST_TAG=$(git describe --abbrev=0)
    - export VERSION=$(if [[ "$CI_COMMIT_TAG" == "" ]]; then echo ""; else echo $CI_COMMIT_TAG | cut -c 2-; fi)
    - if [[ "$VERSION" != "" ]]; then python3 setup.py setopt --command=metadata --option=version --set-value=$VERSION; fi
    - echo VERSION=$VERSION
    - python3 setup.py bdist_wheel
  only:
    - branches
    - tags
  artifacts:
    paths:
      - dist
    expire_in: 1 day

deploy:
  stage: deploy
  variables:
    TWINE_PASSWORD: '$CI_CUSTOM_REGISTRY_PASSWORD'
    TWINE_USERNAME: '$CI_CUSTOM_REGISTRY_USER'
  script:
    - pip3 install twine
    - python3 -m twine upload --repository-url $KYPO_PYPI_UPLOAD_URL dist/*
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      changes:
        - setup.cfg
    - if: $CI_COMMIT_TAG
