image: python:3.7

variables:
  PYTHON_TAG: py3
  ABI_TAG: none
  PLATFORM_TAG: any
  PACKAGE_EXTENSION: whl

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - python3 setup.py bdist_wheel
    - python3 -m pip install --user --upgrade twine
    - echo "[distutils]" >> ~/.pypirc
    - echo "index-servers = gitlab" >> ~/.pypirc
    - echo "[gitlab]" >> ~/.pypirc
    - echo ’repository :\  https://gitlab.fi.muni.cz/api/v4/projects/14820/packages/pypi’>> ~/.pypirc
    - echo "username = __token__" >> ~/.pypirc
    - echo "password = J-ny5gnsNvFmbisGH9WP" >> ~/.pypirc
    - python -m twine upload --repository gitlab dist/*
  only:
    - branches
    - tags
  tags:
    - shared-fi
  artifacts:
    paths:
      - dist
    expire_in: 1 day

deploy:
  image: curlimages/curl:latest
  stage: deploy
  script:
    - python -m twine upload --repository gitlab dist/*
  dependencies:
    - build
  only:
    - tags
  tags:
    - shared-fi
