---
# Configuration of all router devices

- name: Enable IP forwarding
  copy:
    dest: "/etc/sysctl.conf"
    content: "net.ipv4.ip_forward=1"

- name: Restarting procps service
  command: /etc/init.d/procps restart

- name: Add server alias
  lineinfile:
    path: /etc/hosts
    line: 10.10.20.5 server

- name: Add home alias
  lineinfile:
    path: /etc/hosts
    line: 10.10.30.5 home

- name: Add router alias
  lineinfile:
    path: /etc/hosts
    line: 10.10.20.1 router

- name: Add router alias
  lineinfile:
    path: /etc/hosts
    line: 10.10.30.1 router

- name: Add router alias
  lineinfile:
    path: /etc/hosts
    line: 172.18.0.5 router

- name: Add br alias
  lineinfile:
    path: /etc/hosts
    line: 172.18.0.1 br

- name: Delete default gateway
  command: route del default

- name: Add default path to border router
  command: route add default gw 172.18.0.1 eth3
...